### ISSUE TITLE
Create package/repo for installing under Linux esp Ubuntu 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [abulka/pynsource#1]
```
Need a rpm for easy installation on linux.


```

Original issue reported on code.google.com by `abu...@gmail.com` on 14 Nov 2007 at 5:53

**Comment by wonko21** [comment]
One could use https://build.opensuse.org for packaging fro various Distros. Not just RPM (RH,Suse) based but also pkg based (debian,ubuntu) ones.

**Comment by abulka** [comment]
Done - see Linux snap installer (install on any distro using Snapcraft)
http://bit.ly/pynsource-snap
