### ISSUE TITLE
Error during AST ALSM conversion

### ISSUE THREAD

**Issue by tsaoyu** [abulka/pynsource#103]
Hi Andy,

I have encountered the following error: 

```
Error during conversion of python AST into ALSM model: 'Attribute' object has no attribute 'id'
```

on [this python file](https://github.com/ray-project/ray/blob/master/rllib/policy/tf_policy.py).

Best regards,

**Comment by abulka** [comment]
Pending binary release 1.81 will contain this fix - otherwise the fix is in the source code on master.

**Comment by abulka** [comment]
Binaries, Installers and Snaps containing this fix are built and are now available: https://github.com/abulka/pynsource/releases 

Thanks for your patience.
