### ISSUE TITLE
AttributeError during payment for Pro edition.

### ISSUE THREAD

**Issue by mmtechslv** [abulka/pynsource#106]
Due to the following error, it is impossible to purchase the Pro edition.

```
AttributeError at /buy
'tuple' object has no attribute 'get'
...
```

**Comment by abulka** [comment]
Hi,

Sorry about the error - it seems that your card had insufficient funds.  Looking in the logs I see

    '{\n  "error": {\n    "charge": "ch_3K1b2ACDdHJDyZ2n1vl98pfI",\n    "code": "card_declined",\n    "decline_code": "insufficient_funds",\n    "doc_url": "https://stripe.com/docs/error-codes/card-declined",\n    "message": "Your card has insufficient funds.",\n    "type": "card_error"\n  }\n}\n' message='API response body'

I'll have to look into why the exception is ocurring in this case - looks like something weird in a [Django library](https://stackoverflow.com/questions/40513201/django-clickjacking-protection-resp-getx-frame-options-nonetype).

Please try again with a different card or with funds in your card - it should work as purchases goes through all the time.

**Comment by mmtechslv** [comment]
Thanks for the quick reply! I will check with a different card.
