### ISSUE TITLE
pynsource macos 1.84 install issue on High Sierra (10.13.6)

### ISSUE THREAD

**Issue by teunispolak** [abulka/pynsource#112]
I've  instructed Gatekeeper to allow Apps from anywhere to be installed: Preferences>>Security & Privacy>>General under "Allowed apps downloaded from:" has the third radio button "Anywhere" selected. I'm using MacOS High Sierra (10.13.6).

When I right-click open the unzipped Pynsource v 1.84 app I get the dialog with three options, one of which is to Open the app. When I select Open, the icon bounces another 3 - 4 times in the dock and then completely disappears.

If I do not unzip the pynsource app from the macos 1.84 zip file but build the application via Homebrew (brew install pynsource), the result is exactly the same: right click, Open, 3 - 4 bounces and gone.

The moment the app disappears into thin air the system error log shows the following two consecutive messages:
```
Jun 11 23:07:01 iMac com.apple.xpc.launchd[1] (com.apple.xpc.launchd.oneshot.0x10000008.Pynsource[5900]): Service exited with abnormal code: 255
Jun 11 23:07:01 iMac systemstats[74]: assertion failed: 17G65: systemstats + 914800 [D1E75C38-62CE-3D77-9ED3-5F6D38EF0676]: 0x40
```
Once the app has disappeared after the 3 - 4 bounces, I cannot open it again. I have to remove the app and re-install it, either from the downloaded zip file or via a Homebrew installation.

Is there anything you could advise me to do?

**Comment by abulka** [comment]
You probably need to upgrade to a later version of Mac OS. Probably Mojave, but possibly even later. 

I used to build Pynsource in a VM using the oldest Mac OS I could, which made it compatible with all subsequent OS versions. But I've stopped doing that. 

The brew cask simply unzips the same binary, thus would not solve the problem. You could build from source using the instructions provided in the readme.

**Comment by teunispolak** [comment]
Thanks for your lightning-fast response. I've built Pynsource from source; the instructions were very clear.
