### ISSUE TITLE
Design PyNsource icon and logo

### ISSUE THREAD

**Issue by GoogleCodeExporter** [abulka/pynsource#30]
```
Design PyNsource icon and logo - for use in the standalone .exe and for the 
website as a logo.
```

Original issue reported on code.google.com by `abu...@gmail.com` on 2 Sep 2012 at 4:22

https://app.leanboard.io/board/8e502205-6195-478d-9e0a-39a6303b5859

**Comment by abulka** [comment]
Done - quite a while ago!
