### ISSUE TITLE
Printing under Mac OsX spools multiple pages

### ISSUE THREAD

**Issue by GoogleCodeExporter** [abulka/pynsource#32]
```
What steps will reproduce the problem?
1.Create a diagram
2.Print

What is the expected output? What do you see instead?

Instead of printing one page, hundreds of pages are spooled very quickly.

```

Original issue reported on code.google.com by `abu...@gmail.com` on 5 Nov 2012 at 10:34

**Comment by abulka** [comment]
Found workaround
https://github.com/wxWidgets/Phoenix/issues/1151
Fixed - kind of.  Still displays 9999, but will only ever print 1 page, so safe to use.
