### ISSUE TITLE
Lines should be able to be deleted

### ISSUE THREAD

**Issue by GoogleCodeExporter** [abulka/pynsource#42]
```
What steps will reproduce the problem?
1.Create two classes;
2.Create a line between them;
3.Try to delete the line.

There is no option for deleting lines.
1.61 Windows 7 64-bit

```

Original issue reported on code.google.com by `cristian...@yahoo.com` on 21 Jul 2014 at 11:18

**Comment by abulka** [comment]
Working on this. OGL library doesn’t seem to have a way of selecting lines, unfortunately.

**Comment by abulka** [comment]
Implemented a r.click on shape menu listing all lines on the shape, allowing any of them to be deleted.
