### ISSUE TITLE
'q' and 'e' keychars sometimes not picked up or chars lost

### ISSUE THREAD

**Issue by GoogleCodeExporter** [abulka/pynsource#46]
```
What steps will reproduce the problem?
1. create two classes
2. select a class, hit 'q'
3. select another class, hit 'e'

What is the expected output? What do you see instead?

expect an association line to be created.
but nothing happens (sometimes),

1. create two classes
2. double click a class
3. edit some method names etc.

What is the expected output? What do you see instead?

expect 'q' and 'e' etc. chars to be entered when typed.  Sometimes those keys 
are swallowed somewhere and cannot be entered as part of a class name or method 
name etc. (sometimes)

NOTE: sometimes q and w and other menu shortcut keys WORK and sometimes they 
DON'T.  Must be some mode thing.
```

Original issue reported on code.google.com by `abu...@gmail.com` on 25 Aug 2014 at 11:18

**Comment by abulka** [comment]
Confirmed - issue still there today, playing with inserting (using I key) classes onto the workspace from scratch.  Classes inserted ok.  the q/w stuff usually works but sometimes not.

**Comment by abulka** [comment]
Seems to happen after invoking Edit/Insert Class...

- Situation repaired by either switching to the Ascii view and back again.
- Situation repaired also by hitting up, left, right arrow.  Down arrow doesn't fix it.
- Situation repaired also by importing some python code and creating new classes that way.

Seems that the `onKeyChar` and `onKeyPress` handlers are unbound from the UmlCanvas shape canvas after adding (as opposed to importing) a new class.

**Comment by abulka** [comment]
Fixed by removing the call to `wxapp.RefreshAsciiUmlTab()` when inserting a new node.
Commit ed11c8341530abd63455f58da01a3da9b6bfb5d7
