### ISSUE TITLE
Windows 10 download link: 'Not Found'

### ISSUE THREAD

**Issue by William-Blackie** [abulka/pynsource#49]
The windows 10 download link is not working, both on this repo as well as your website. Hope this helps others.

**Comment by abulka** [comment]
Fixed - thank you so much. Please try again.
If you have time, please let me know if you successfully installed it.
I have tested installing all the releases, the link was just a typo, so you should be good to go.

**Comment by William-Blackie** [comment]
The link on the repository works correctly and installs fine. One issue is Pynsource's height is larger than my screen height so I cannot move the window on a 1920 x 1080 monitor, this may just be my issue.

I will close the issue as the original issue has been fixed.

Thanks, Will.

**Comment by abulka** [comment]
Hi William,

I checked Pynsource on a Windows 10 VM with resolution set to 1920x1080 and it seems to behave ok - see picture:

<img width="2032" alt="Screen Shot 2019-03-21 at 9 27 32 am" src="https://user-images.githubusercontent.com/11467530/54725584-b9d59900-4bc3-11e9-89de-9db395f1abac.png">

The code controlling this is: `WINDOW_SIZE = (1024, 768)` where its (width, height)

```python
class MainApp(WxAsyncApp):
    def OnInit(self):
            pos=(50, 50),
            size=(0, 0),
        self.frame.SetSize(WINDOW_SIZE)
```

And using my wx inspection tool, the actual frame appears at
```
    pos = (448, 136)
    size = (1024, 768)
```

Perhaps you have a magnified desktop theme or something?

In any case, to help you out, I've added some config options where  you can explicitly set the size and position of the window on startup.   Edit your `pynsource.ini` file to add one or both entries:

```
WindowSize = 200, 400
WindowPosition = 210, 240
```

You can delete or comment out those lines with # if you don't need them.  The location of the config file pynsource.ini is as follows:
        
Windows:
`C:\Users\YOURNAME\AppData\Roaming\Pynsource\pynsource.ini`

Mac:
`~/Library/Preferences/Pynsource/pynsource.ini`
e.g.
`/Users/YOURNAME/Library/Preferences/Pynsource/pynsource.ini`

Linux:
`~/.Pynsource/pynsource.ini`

This new config support is in the source code repo, so you can try it if running from source. It will be released as a binary download in the next several hours.

Hope this help.
Let me know how you go!

cheers,
Andy

**Comment by abulka** [comment]
New binaries 1.74 released http://pynsource.com/download.html
