### ISSUE TITLE
pls open  file withc encoding 

### ISSUE THREAD

**Issue by flexer2018** [abulka/pynsource#69]
pls open the py files with encoding option 
etc as in quick_parse.py line 20 

with open(filename, "r",encoding='utf-8') as f:
adding the encoding support ,will be easy to support the non english language.

thanks you !

**Comment by abulka** [comment]
Thanks for the tip re `utf-8`. I've applied the change and several more needed throughout the codebase - see latest master.

P.S. If you are need a binary build (e.g. have a pro licence perhaps) with this change in it, please let me know the OS and I'll create a beta executable build for you with this latest master.
