### ISSUE TITLE
function annotation ("-> blah") results in error dialog

### ISSUE THREAD

**Issue by sjswerdloff** [abulka/pynsource#79]
an error dialog came up (see below) while importing specific python code.
It appears to be complaining about difficulty parsing a function annotation.

**Comment by sjswerdloff** [comment]
I ran against OnkoDICOM/team2020 and got:
![Screenshot from 2020-08-27 21-00-58](https://user-images.githubusercontent.com/16871837/91504597-b9494200-e921-11ea-8975-1e4c1117f810.png)

**Comment by sjswerdloff** [comment]
I might be misinterpreting the error message because it also says "actual exception ..." about something else.
But the dialog said "please report", so... that's the least I can do if I'm going to try out/use pynsource (kudos, it's the best python reverse engineering tool I've seen).

**Comment by abulka** [comment]
Thank you for reporting this - I will take a look. 

And thanks for the compliment - very encouraging. Also check out my www.gituml.com project which also reverse engineers Python.

**Comment by abulka** [comment]
Thanks for reporting this - latest master should fix this.

If you are a pro customer let me know your os and I'll do a new build for you.

**Comment by abulka** [comment]
Fix also deployed to the sister project [GitUML](https://gituml.com)

E.g. https://gituml.com/fiddle/python/

**Comment by sjswerdloff** [comment]
> Latest master fixes this.
> 
> If you are a pro customer let me know your OS and I'll do a new build for you.

i am not a pro customer (sorry, not using it professionally yet, will purchase if/when I do).
However, I have fetched/pulled and confirmed the issue is resolved!
Thank you (it wasn't stopping me from seeing the big picture, but I appreciate commitment to elimination of bugs).
