### ISSUE TITLE
can't process python3 files with f-strings and {var=} syntax

### ISSUE THREAD

**Issue by lolo26130** [abulka/pynsource#81]
can't process python3.8 files containing f-strings with {var=} syntax
i.e. :

#!/usr/bin/env python3
variable = 'a'
print(f'{variable=}')

![Screenshot_Pynsource_f-string](https://user-images.githubusercontent.com/50276531/95562554-98920300-0a1c-11eb-8935-f9ea4b92e595.png)

**Comment by abulka** [comment]
Thanks for reporting this.

The ability to specify an `=` sign after a variable in an fstring is a Python 3.8 feature. See [f-strings support = for self-documenting expressions and debugging](https://docs.python.org/3/whatsnew/3.8.html). Pynsource will have to be running under Python 3.8 to handle this syntax.

Pynsource release binaries currently run under Python 3.7.

Running the latest master of Pynsource from source under Python 3.8 will allow you to parse this 3.8 syntax.
I hope to update the Pynsource release binaries to Python 3.8 in the next release.
