### ISSUE TITLE
I can't open the section for registering the program. Not open.

### ISSUE THREAD

**Issue by andrew-t34** [abulka/pynsource#82]
I can't enter the received registration code. The input window does not open.
The problem occurs when installing from the application Manager.

**Comment by abulka** [comment]
Hi,

I can confirm the purchase was successful and your serial number was sent ok. 

What operating system are you on? If you are using a Ubuntu snap install of Pynsource from the snap store - that can't be registered and you need to install from one of the binary installers. 

Andy
