### ISSUE TITLE
fc32 snap install pynsource; no text in pynsource-gui

### ISSUE THREAD

**Issue by uhu53** [abulka/pynsource#87]
in pynsource-gui no text, but only rectangles shown. 
see attachment.

btw: what do you mean with 'foxed parsing exceptions with python3.8' ?

thx

![pynsource-no-text](https://user-images.githubusercontent.com/55461304/111599775-f2b7a100-87d0-11eb-8827-0fa45082f164.png)

**Comment by uhu53** [comment]
lsof revealed the debug.log

[debug.log](https://github.com/abulka/pynsource/files/6162709/debug.log)

**Comment by uhu53** [comment]
# lsof |grep pynsource |grep "No such file" reveals (lots of) missing files in the snap pynsource package.
see attachment:
[missg-files.txt](https://github.com/abulka/pynsource/files/6164154/missg-files.txt)
a wild guess: the missing text in pynsource-GUI might be due to the missing locale files under:
/snap/pynsource/8/gnome-platform/usr/lib/locale/

If it were not snap's r/o FS I would                   {hail to the sacred security ! }
# cd /snap/pynsource/8/gnome-platform
 # mkdir usr; mkdir usr/lib; 
# cd usr/lib
# ln -s /usr/lib/locale locale                              {my fedora 32)
and give it a try

what do you think?

**Comment by uhu53** [comment]
managed to get it running from source.
had to comment the udpate check in: pynsource-gui.py ln: 368/369
see attachment: 
[pynsource-gui-error.txt](https://github.com/abulka/pynsource/files/6164616/pynsource-gui-error.txt)

hope I can uninstall the snap thing

**Comment by abulka** [comment]
Not sure why those files are missing - snap runs fine on Ubuntu systems. I’ve never run or tested on fedora, sorry.
