### ISSUE TITLE
cannot enter license in source version !

### ISSUE THREAD

**Issue by uhu53** [abulka/pynsource#88]
on fedora  #32 I use the source version (due to issues with the snap version, see issue #87).
i bought a pro license but cannot enter the license code.
The issue is in pynsource-gui.py ln:1318
        from gui.settings import enter_license
the method enter_license is not found
hence on line 1327 the debugger says
Traceback (most recent call last):
  File "/opt/pynsource-1.77/src/pynsource-gui.py", line 1327, in OnEnterLicense
    result = enter_license(name, serial)
NameError: name 'enter_license' is not defined

pls advise !

**Comment by abulka** [comment]
You cannot license the open source or snap versions. You need to download and run a binary version.

**Comment by abulka** [comment]
I've built a fedora binary for you.

Run the prebuilt [Fedora Pynsource binary](https://github.com/abulka/pynsource/releases/download/version-1.77/pynsource-1.77-fedora-31.zip) from the terminal `./Pynsource` and it should start up ok, even though its of a type `application/x-sharedlib`. 

You should be able to register this version and get all the Pro features like zoom.

**Comment by uhu53** [comment]
thanks for the effort, but unfortunately not. 
Seems to be a glibc version issue. In the readme of pynsource-fedora you mention fedora 31. -- With my fedora 32 I still have glibc-2.31 and glibc-common-2.31, glibc-2-32 only comes with fedora 33 onwards - (if I don't mixup things)
The error message starting up Pynsource:
[startup-error.txt](https://github.com/abulka/pynsource/files/6170224/startup-error.txt)

**Comment by abulka** [comment]
Hmmm, I’ve never used Fedora before, so I installed the latest version 33 from https://getfedora.org/en/workstation/download/  into a VM and got pynsource running - I documented the steps https://github.com/abulka/pynsource/blob/master/INSTALL-TIPS.md

I then packaged with pyinstaller. Looks like I accidentally referred to fedora 31 when in reality the zip and readme should refer to 33.

Looks like you need an installer built on an earlier version of Fedora!?
