### ISSUE TITLE
I can't enter the license key. Sub-window for license is not opened. 

### ISSUE THREAD

**Issue by KevinRyu** [abulka/pynsource#89]
Hello,

As I mentioned in title, I want to register my license.
I run it in windows10 pro. I added the error message the following.

Running Community Edition
LOG_FILENAME is C:\Users\xxx\AppData\Roaming\Pynsource\debug.log

Error checking for latest version during startup - you are probably running on fedora? Exception bypassed.
pynsource-gui.py:373: RuntimeWarning: coroutine 'MainApp.check_for_updates' was never awaited
  print("Error checking for latest version during startup - you are probably running on fedora? Exception bypassed.")
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Traceback (most recent call last):
  File "pynsource-gui.py", line 1322, in OnEnterLicense
    from gui.settings import enter_license
ImportError: cannot import name 'enter_license' from 'gui.settings' (C:\pynsource\pynsource-master\src\gui\settings.py)

**Comment by abulka** [comment]
Hi - thanks for the purchase.

You need to use a binary downloaded version of Pynsource for the rego to work  - looks like you are running from the source code?

cheers, 
Andy

**Comment by KevinRyu** [comment]
Hi.

That's right. I tried to register with source code version. I already
searched closed issue and found answer. Now I can use pro-version by using
binary installer. Thanks for your reply.

So, I will close this issue.

2021년 4월 21일 (수) 오후 4:41, Andy Bulka ***@***.***>님이 작성:
