### ISSUE TITLE
macOS binaries - How to Open Apps from “Unidentified Developers”

### ISSUE THREAD

**Issue by poke1024** [abulka/pynsource#90]
For anyone wanting to run the downloaded macOS binaries, you need to do the gatekeeper thing:

```
xattr -dr com.apple.quarantine /path/to/pynsource.app
```

Maybe this could be mentioned somewhere on the download page?

**Comment by abulka** [comment]
Yes I should put something in the documentation, as I'm too cheap to pay Apple for a yearly developer license to sign the executables. 

I simply recommend that people right click / open the app the first time and say yes, trust. I haven't heard of the above command line trick - presumably it accomplishes the same thing and marks the app as ok to simply double click on?

**Comment by poke1024** [comment]
Unfortunately not. At least on the lastest version of macOS (Big Sur) the right-click & open trick does not work in this case for some reason. It starts to open, but then quits with an error. I also tried to open the bundle and open the actual binary with the right-click-open command - does not work either. The explicit `xattr` command works though.
