### ISSUE TITLE
PlantUML images/exports are clipped

### ISSUE THREAD

**Issue by poke1024** [abulka/pynsource#91]
For example, see the rightmost box in this export:

![embeddings_uml](https://user-images.githubusercontent.com/11859538/120623115-b60a5600-c45f-11eb-9ae8-6fd528b9af57.png)

Not sure if this is a PlantUML issue...

**Comment by abulka** [comment]
I think it is a PlantUML issue re hitting size limits on the free public PlantUML API.
There are instructions on how to use your own instance of PlantUML in the Pynsource help (in the app) as well as in #51.

**Comment by poke1024** [comment]
Ok, thanks for the link. I will set up a local PlantUML installation then.
