### ISSUE TITLE
Variable annotation triggers exception 'Subscript' object has no attribute 'id'

### ISSUE THREAD

**Issue by gjdm** [abulka/pynsource#93]
Variable annotation (e.g. "self.pages: List[SnapFilterView2D] = list()") triggers exception 'Subscript' object has no attribute 'id'

![image](https://user-images.githubusercontent.com/519788/121062859-e20e3a00-c7c5-11eb-99e6-86f08c6ea3af.png)

gjdm

**Comment by abulka** [comment]
Thank you for reporting this.

**Comment by abulka** [comment]
Tried to reproduce this running under Python 3.9 parsing the following:

```python
class A:
    def method1(self):
        self.pages: List[SnapFileView2D] = list()
```

and got no errors. 

Hmm - perhaps this error only happens with lower version of Python - will need to check. As it stands, it looks promising that no changes to the Pynsource parser are needed, only a Python version bump. That is, assuming the above source code reproduces the problem.

**Comment by abulka** [comment]
Tested parsing this on Mac using official release which uses Python 3.7 internally - worked ok. 

But on Linux the official snap release does exhibit the problem, but running under Python 3.7 from source code does not. Mysterious.  Will investigate further.

**Comment by abulka** [comment]
Changed visit_AnnAssign() in parser to fix this, passes now under all Python versions.

**Comment by abulka** [comment]
Latest master branch and `1.78 beta` [binary release](https://github.com/abulka/pynsource/releases/tag/untagged-3d0387717ccd1c229bc3) should have fixed this.
Official `1.78` release only a few days away.
