### ISSUE TITLE
Walrus operator marked as syntax error

### ISSUE THREAD

**Issue by alexchandel** [abulka/pynsource#94]
The new walrus operator is marked as a syntax error in Pynsource 1.77:

```
Syntax error in parsing
'.../main.py'

'invalid syntax' on line 14:

if (pair := chairs.get(number, None)) is None:
```

**Comment by abulka** [comment]
This seems to pass OK under Python 3.9

```python
def test_issue_walrus_issue_94(self):
    source_code = dedent("""
        if (pair := chairs.get(number, None)) is None:
            pass
    """
    )
    pmodel, debuginfo = parse_source(source_code, 
                                        options={"mode": 3}, 
                                        html_debug_root_name="test_issue_walrus_issue_94")
    self.assertNotIn("error", pmodel.errors)
```

Perhaps this error only happens with a lower version of Python - will need to check. As it stands, it looks promising that no changes to the Pynsource parser are needed, only a Python version bump. That is, assuming the source code fragment above reproduces the problem.

**Comment by alexchandel** [comment]
I think walrus entered in 3.8.  I have 3.9 installed in `/usr/local` (macOS) but I assume you don't use that.  Source fragment was something like:

```py
chairs: dict[int, str]
number: int
...
if (pair := chairs.get(number, None)) is None:
    ...
```

**Comment by abulka** [comment]
Latest master branch and `1.78 beta` [binary release](https://github.com/abulka/pynsource/releases/tag/untagged-3d0387717ccd1c229bc3) should have fixed this.
Official `1.78` release only a few days away.

Note: Ubuntu Snap is stuck at Python 3.6 till Canonical fix their Snapcraft core20 stuff.
