### ISSUE TITLE
(Pro/Community) PlantUML render cutting off bottom edge of elements

### ISSUE THREAD

**Issue by abclution** [abulka/pynsource#95]
Having some issues with the PlantUML layout cutting off the bottom edge of the render.
Bought the "Pro" License in case it was a problem with the autofit algorithm but  it appears this is not the issue. Please see photos below.

![image](https://user-images.githubusercontent.com/10130237/122886701-dafc3580-d348-11eb-9a46-dedf7954df86.png)

![image](https://user-images.githubusercontent.com/10130237/122886729-e2234380-d348-11eb-90c0-8a02917bc70b.png)

**Comment by abulka** [comment]
Probably a limit of the community plantUML server - look in the built in Pynsource help and in the GitHub  issues for info on setting up a local server to render larger diagrams.
